name: html-migration
on:
  pull_request:
    types:
    - 'opened'
    - 'synchronize'

jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: html-migration
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7.5
          bundler-cache: true
      - name: config
        run: bundle config set with migration
      - name: install
        run: bundle install
      - name: build
        run: JEKYLL_ENV=${{env.JEKYLL_ENV}} bundle exec jekyll build --trace
      - uses: EndBug/add-and-commit@v7
        with:
          add: '_posts/'
          default_author: github_actions
          message: 'Migrated HTML books, please review build log for possible manual intervention'
